### ISSUE TITLE
Block just greyed out

### ISSUE THREAD

**Issue by damianburrin** [sabas1080/uBit_BMP085#1]
Hi,

Really want to use this as its the only one that has the altitude function rather than just pressure and temp.  It imports but just give me a grey icon.  I can add the block but then just get compliation errors.

Any ideas?

Thanks

**Comment by sabas1080** [comment]
Hi @damianburrin 

I just tried with micro bit and everything ok, it is an example

![example_bmp180](https://user-images.githubusercontent.com/2874292/47677875-ea218a00-db85-11e8-9a26-8ecaa651ed7d.png)

**Comment by sabas1080** [comment]
Note: the pressure module is not fully working, you are welcome to contribute

**Comment by damianburrin** [comment]
![bmp](https://user-images.githubusercontent.com/18092613/47680616-389f4a80-dbbf-11e8-85f2-9caf88eb0879.jpg)

Hi,

Thanks for getting back to me.  The print screen is what I get.  I notice the current PXT editor on microbit.org has been updated.

Really not sure what is happening.  I'll do my best to contribute and fix but any pointers would be great

**Comment by sabas1080** [comment]
please switch to mode javascript and explorer error

![microsoft makecode for micro bit](https://user-images.githubusercontent.com/2874292/47682573-76d24500-db92-11e8-81cf-39d241971493.png)

**Comment by damianburrin** [comment]
Hi, Thank you for your continued support.

This is what i see in the javascript mode
![exploermode](https://user-images.githubusercontent.com/18092613/47742112-d3f1f780-dc73-11e8-9cd3-0bb2763ca32d.jpg)

It gives the same error as before but i can't see anything different.

As an addendum have you seen this
![makecode](https://user-images.githubusercontent.com/18092613/47742167-eff59900-dc73-11e8-8f06-64ad9ddf6bbe.JPG)

The editor has been updated.  I tried the same blocks on the old editor and it does work so there's been a change somewhere that's making incompatible with the current version.

I notice the data i get isn't what i'd expect pressure or altitude wise - comes out differently to the values i get when addressing it in C via the arduino but you did say there was some issues with it but I guess the issue of it not working is down to the new editor,

Any help would be appreciated.

Thanks you

**Comment by sabas1080** [comment]
Yes, not working is down to the new editor

with the new editor theoretically you should be able to pass everything to typescript and leave C, unfortunately I can do that for a few months

**Comment by damianburrin** [comment]
Ah - ok At least we have replicated the problem.  I'm not competent enough to be able to do much to help here but if you do get round to a fix let me know and i'll happily test.  I

Much appreciated
Damian

**Comment by sabas1080** [comment]
Hi @damianburrin It was updated for the latest microbit version you can try please

**Comment by damianburrin** [comment]
Yep seems to compile now.  Thank you

**Comment by sabas1080** [comment]
thanks to you
